"""create User and Music

Revision ID: 137cad260433
Revises: 
Create Date: 2023-11-05 14:51:58.923395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137cad260433'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music')
    # ### end Alembic commands ###
